#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := ESP32_ABC150

EXTRA_COMPONENT_DIRS := $(PWD)/components/AmpleNetwork $(PWD)/components/ABC150

include $(IDF_PATH)/make/project.mk

